# GAN-BERT

![](../img/ganbert.jpg)

Dados para o GAN-BERT são organizados nos arquivos `labeled.tsv`, `unlabeled.tsv` e `test.tsv`

In [1]:
!head ../../ganbert_subj/data/subj_un_001/labeled.tsv

fine_label utterance
SUBJ:0 a chilling tale of one of the great crimes of th century france the murder of two rich women by their servants in 
SUBJ:1 fate brings emma and bret together and they discover shared disdain for clients who collect art to impress others follow the current trend or think only in terms of investment value 
SUBJ:0 wilco fans will have a great time and the movie should win the band a few new converts too 
SUBJ:0 functions as both a revealing look at the collaborative process and a timely tongue in cheek profile of the corporate circus that is the recording industry in the current climate of mergers and downsizing 
SUBJ:0 succeeds very well in its primary aim of making us gasp 
SUBJ:1 based on frances mayes memoir of the same name 
SUBJ:0 the main characters are simply named the husband the wife and the kidnapper emphasizing the disappointingly generic nature of the entire effort 
SUBJ:1 her father invented the world panorama for use by the authorities but was tur

In [2]:
!head ../../ganbert_subj/data/subj_un_001/unlabeled.tsv

fine_label utterance
UNK:UNK vile and tacky are the two best adjectives to describe ghost ship
UNK:UNK in the meantime the british forces back at the encampment march off to meet the american forces for a grand battle which will rage for hours
UNK:UNK netes father becomes bitter and introvert but nete insists that he come to live with her and her family the few weeks he has left
UNK:UNK the latest installment in the pokemon canon pokemon ever is surprising less moldy and trite than the last two likely because much of the japanese anime is set in a scenic forest where pokemon graze in peace
UNK:UNK a documentary examining the december nd assassination of microsoft ceo bill gates in los angeles and the group of key players seeking to unravel the mystery of his alleged assassin as well as the circumstances surrounding his death
UNK:UNK francophiles will snicker knowingly and youll want to slap them
UNK:UNK the jokes are sophomoric stereotypes are sprinkled everywhere and the acting ranges

## Exemplo de entrada do BERT

INFO:tensorflow:*** Example ***

INFO:tensorflow:guid: train-SUBJ:1 arrested and imprisoned in a juvenile detention facility leland comes in contact with an aspiring writer and prison teacher pearl madison cheadle 

INFO:tensorflow:tokens: [CLS] arrested and imprisoned in a juvenile detention facility le ##land comes in contact with an aspiring writer and prison teacher pearl mad ##ison ch ##ead ##le [SEP]

INFO:tensorflow:input_ids: 101 3950 1105 8269 1107 170 15031 13826 3695 5837 1931 2502 1107 3232 1114 1126 25850 2432 1105 3315 3218 24837 6340 7614 22572 12393 1513 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

INFO:tensorflow:input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

INFO:tensorflow:segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

INFO:tensorflow:label: SUBJ_1 (id = 2)


Modelo BERT utilizado https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip

### Dados

INFO:tensorflow:*** Features ***

INFO:tensorflow:  name = input_ids, shape = (64, 64)

INFO:tensorflow:  name = input_mask, shape = (64, 64)

INFO:tensorflow:  name = is_real_example, shape = (64,)

INFO:tensorflow:  name = label_ids, shape = (64,)

INFO:tensorflow:  name = label_mask, shape = (64,)

INFO:tensorflow:  name = segment_ids, shape = (64, 64)


## Saída do BERT


```
tensor([[-0.3124,  0.5256,  0.9981,  ...,  0.9997, -0.7138,  0.9547],
        [-0.5034,  0.6236,  0.9995,  ...,  0.9999, -0.1922,  0.9475],
        [-0.0393,  0.4882,  0.9965,  ...,  0.9993, -0.9119,  0.9660],
        ...,
        [-0.0552,  0.4531,  0.9954,  ...,  0.9994, -0.9394,  0.9714],
        [-0.5643,  0.5076,  0.9997,  ...,  0.9999, -0.0433,  0.9664],
        [-0.2110,  0.4298,  0.9980,  ...,  0.9995, -0.6424,  0.9537]],
       device='cuda:0', grad_fn=<TanhBackward0>)
torch.Size([64, 768])
```

## Saída do Gerador

```
tensor([[ 0.2726, -0.0464, -0.2440,  ..., -0.2718,  0.2842, -0.1519],
        [ 0.4422, -0.1188, -0.0544,  ..., -0.4002,  0.0767, -0.0866],
        [ 0.2127, -0.0400, -0.3291,  ..., -0.3526,  0.3529, -0.2562],
        ...,
        [ 0.4526, -0.0307, -0.1168,  ..., -0.1448,  0.0499, -0.0420],
        [ 0.3388, -0.0700, -0.2178,  ..., -0.1839,  0.3749, -0.0271],
        [ 0.2655, -0.0607, -0.1258,  ..., -0.3140,  0.3294, -0.1767]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
torch.Size([64, 768])
```

### Variáveis treináveis

INFO:tensorflow:**** Trainable Variables ****

INFO:tensorflow:  name = bert/embeddings/word_embeddings:0, shape = (28996, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/embeddings/token_type_embeddings:0, shape = (2, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/embeddings/position_embeddings:0, shape = (512, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/embeddings/LayerNorm/beta:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/embeddings/LayerNorm/gamma:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/query/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/query/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/key/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/key/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/value/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/self/value/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/dense/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/LayerNorm/beta:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/attention/output/LayerNorm/gamma:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/intermediate/dense/kernel:0, shape = (768, 3072), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/intermediate/dense/bias:0, shape = (3072,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/output/dense/kernel:0, shape = (3072, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/output/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/output/LayerNorm/beta:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_0/output/LayerNorm/gamma:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/query/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/query/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/key/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/key/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/value/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/self/value/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/dense/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/LayerNorm/beta:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/attention/output/LayerNorm/gamma:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/intermediate/dense/kernel:0, shape = (768, 3072), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/intermediate/dense/bias:0, shape = (3072,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/output/dense/kernel:0, shape = (3072, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/output/dense/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/output/LayerNorm/beta:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_1/output/LayerNorm/gamma:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/query/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/query/bias:0, shape = (768,), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/key/kernel:0, shape = (768, 768), *INIT_FROM_CKPT*

INFO:tensorflow:  name = bert/encoder/layer_2/attention/self/key/bias:0, shape = (768,), *INIT_FROM_CKPT*

...

## Parâmetros

In [3]:
#--------------------------------
#  Transformer parameters
#--------------------------------
max_seq_length = 64
batch_size = 64

#--------------------------------
#  GAN-BERT specific parameters
#--------------------------------
# number of hidden layers in the generator, 
# each of the size of the output space
num_hidden_layers_g = 1; 
# number of hidden layers in the discriminator, 
# each of the size of the input space
num_hidden_layers_d = 1; 
# size of the generator's input noisy vectors
noise_size = 100
# dropout to be applied to discriminator's input vectors
out_dropout_rate = 0.2

# Replicate labeled data to balance poorly represented datasets, 
# e.g., less than 1% of labeled material
apply_balance = True

#--------------------------------
#  Optimization parameters
#--------------------------------
learning_rate_discriminator = 5e-5
learning_rate_generator = 5e-5
epsilon = 1e-8
num_train_epochs = 10
multi_gpu = True
# Scheduler
apply_scheduler = False
warmup_proportion = 0.1

## Redes

### Gerador

* Camadas linerares (1 camada, 512 neurônios)
* Função de ativação leakyReLU (0.2)
* Dropout (0.1)
* Entrada noise (100)
* Saída (512)

### Discriminador

* Camadas linerares (1 camada + 1 linear/softmax, 512 neurônios)
* Função de ativação leakyReLU (0.2)
* Dropout (0.1)
* Entrada (512)
* Saída (2 + 1 fake)

# GAN-TEXTGEN

![](../img/gan-textgen.png)

Dados para o GAN-TEXTGEN

In [4]:
!head ../data/subj/train_un_001.txt

0	the problem is that the movie has no idea of it is serious or not . 
1	on an out of control train holding hostages and high-tech bio-weapons agent kristoff ( van damme ) becomes a one man army to derail the terrorists and save the lives of everyone on board ! 
0	parker cannot sustain the buoyant energy level of the film's city beginnings into its country conclusion
1	emory , a former governor of his tribe , is reunited with his son larry , via the help of a friend , sky montgomery , who invites larry to travel from the old pueblo to the new " big city " to join his father at a photo-art exhibition hosted by sky . 
0	this is cool , slick stuff , ready to quench the thirst of an audience that misses the summer blockbusters . 
1	rio danisworo ( marcellius siahaan ) is a rigid " all about business " young profesional . 
0	it's fun , but the code-talk will fly right over everyone's head
1	while treating a homicide detective for smoking , hypnotherapist michael strother has a telepathic vi

In [5]:
!tail ../data/subj/train_un_001.txt

UNK	due to unfortunate circumstances he is forced to flee his former brothers in arms . 
UNK	but all is not smooth in the rockies , as their relationship accelerates - cultural differences , family issues , former loves and life-altering challenges threaten to shake things up . 
UNK	not only are the film's sopranos gags incredibly dated and unfunny , they also demonstrate how desperate the makers of this 'we're -doing-it-for -the-cash' sequel were . 
UNK	an interesting , if not entirely successful , biography of two extraordinary personalities . 
UNK	los angeles' little tokyo's foremost studio photographer , miyatake smuggled a lens and film holder into the u . s . wwii camp he was incarcerated in and captured life behind barbed wire with a makeshift camera made of scrap wood . 
UNK	feels less like a cousin to blade runner than like a bottom-feeder sequel in the escape from new york series . 
UNK	offers a gentle summer fantasy for both grown-ups and little ones . 
UNK	crush could be th

## Saída do pipeline

```
tensor([[    1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,  2181,     7,
           655,   540,    17,    65,    13,    78,   141,   169,    86,   641,
            70,     6,    11,   104,  2491,    14,    76,     2],
            ...
shape = torch.Size([8, 118])
```

## Saída do gerador

```
tensor([[ 4090, 11000,  7578,  5285,  7228, 19811,  7131, 15849, 14560, 10865,
          2648, 12967,    68,  1394, 11009, 18530,  2722, 18712,  8821,   420,
         13117,  2491,   217, 16313, 15592,  9648,  4268,  9140,  2084, 17412,
         20138,  1730, 16664,  4659,  6740, 18687,  3150,  8856,  5743,  1525,
          5393,  5393,  4664, 14332,  4017, 17118, 21387,  3703,  7443, 19710,
          3823,  7529, 11767, 16162, 10091,   783,  4891, 11345, 16871, 13877,
         13877,  1578, 14021, 20042,  8622,  7886,  8943,   600,  9484,  3539,
         14814, 12075,  6244, 13223,  4674, 10574, 18444, 20211, 21027,  4918,
          8894,  3160, 17645, 10373, 19883,  3757, 17242, 20366, 18851, 15860,
         11838,   475, 12367,  2487, 20663,  2324,  1509,  3673,  6288, 19292,
         12287,  9455, 16928,  2197, 11774, 16742,  8020, 12560, 12165,  5217,
          3982, 13858,  4845, 19026, 21232, 16566,  1803, 18652],
shape = torch.Size([8, 118])
```

## Parâmetros

In [6]:

print_each_n_step = 50
num_train_epochs = 10
noise_size = 100
max_seq_length = 200
batch_size = 8
epsilon = 1e-8
word2vec_len = 300

## Redes

### Gerador

* Camadas GRU (1 camada, 64 neurônios)
* Sem função de ativação
* Dropout (0.1)
* Entreda noise (100)
* Saída (29405)

### Discriminador

* 1 camada LSTM (+ 1 linear/softmax), 64
* Sem função de ativação
* Dropout (0.1)
* Embedding do texto na entrada com vetores word2vec prontos
* Entrada (300)
* Saída (2 + 1 fake)